### PR TITLE
Add command to quickly install all dependencies

### PR DESCRIPTION
**Pull request by solarkraft**
This really reduces the time required for beginners to get up and running with Gala development.

### CODE REVIEW

**Comment by arshubham** [comment]
Doesn't `sudo apt build-dep gala` achieve the same?

**Comment by peteruithoven** [comment]
@arshubham as I've included in the follow tips, that only works when the dependencies match the last published version.
https://github.com/elementary/website/blob/ee96472e5f8483a59590ff7628a23fee94c64d0f/docs/code/os-dev.md

**Comment by danrabbit** [comment]
I don't think we want to add distro specific commands like this to the README

**Comment by ricotz** [comment]
I am with @danrabbit here, sorry.

**Pull request closed without merging**
