### PR TITLE
Add missing languages to LINGUAS files

### PR DESCRIPTION
**Pull request by ryonakano**
If we don't add these languages, they won't be available to translate in Weblate, and people who speak these languages and want to translate into them can not submit their translation.

### CODE REVIEW

**Comment by ryonakano** [comment]
@leonardo-lemos Could you merge this? I have no right to merge.

**Comment by leonardo-lemos** [comment]
> 
> 
> @leonardo-lemos Could you merge this? I have no right to merge.

Only @ricotz can merge this.

**Comment by ryonakano** [comment]
@ricotz These po files have no translations because they're newly generated and added in this PR. Since I added lacking language codes to the LINGUAS file in this PR, I thought I need to generate and add po files for these languages.

**Comment by ricotz** [comment]
@ryonakano And what is the reason to add the "missing" languages?

**Comment by ricotz** [comment]
@ryonakano I assume this is to enable weblate picking this up and providing these missing languages to be translated. If so, this kind of information should be part of the merge proposal description.

**Comment by ryonakano** [comment]
@ricotz Yes, you're right. if we don't add these languages, they won't be available to translate in Weblate, and people who speak these languages and want to translate into them can not submit their translation.
Yes, I should have written these information first. I'm sorry.

**Comment by ricotz** [comment]
Pushed https://github.com/elementary/gala/commit/dbbfb50f9b95439d0ba79e89325dd4b36c92049b
Let's see if this is enough.

**Comment by ryonakano** [comment]
Thank you.

**Pull request closed without merging**
