### PR TITLE
Schedule dark mode

### PR DESCRIPTION
**Pull request by meisenzahl**
Related to https://twitter.com/DanielFore/status/1277316869414768640

### CODE REVIEW

**Comment by meisenzahl** [comment]
I have problems implementing the logic because with a modified Ubuntu 20.04 and the daily PPAs I have the following errors:

```
$ meson build --prefix=/usr
The Meson build system
Version: 0.53.2
Source dir: /media/sf_shared/Projekte/github.com/meisenzahl/gala
Build dir: /media/sf_shared/Projekte/github.com/meisenzahl/gala/build
Build type: native build
Project name: gala
Project version: 3.3.2
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Vala compiler for the host machine: valac (valac 0.48.7)
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: Project targeting '>= 0.48.0' but tried to use feature introduced in '0.49.0': / with string arguments
Configuring config.h using configuration
Library config found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency glib-2.0 found: YES 2.64.2
Run-time dependency gobject-2.0 found: YES 2.64.2
Run-time dependency gio-2.0 found: YES 2.64.2
Run-time dependency gmodule-2.0 found: YES 2.64.2
Run-time dependency gtk+-3.0 found: YES 3.24.18
Run-time dependency gdk-x11-3.0 found: YES 3.24.18
Run-time dependency gee-0.8 found: YES 0.20.3
Run-time dependency libbamf3 found: YES 0.5.4
Run-time dependency plank found: YES 0.11.89
Run-time dependency granite found: YES 5.5.0
Run-time dependency gnome-desktop-3.0 found: YES 3.36.2
Run-time dependency gnome-settings-daemon found: YES 3.36.1
Library m found: YES
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libmutter-2 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-3 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-4 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-5 found: NO (tried pkgconfig and cmake)
Run-time dependency libmutter-6 found: YES 3.36.2
Dependency libmutter-6 found: YES 3.36.2 (cached)
Run-time dependency mutter-cogl-6 found: YES 3.36.2
Run-time dependency mutter-cogl-pango-6 found: YES 3.36.2
Run-time dependency mutter-cogl-path-6 found: YES 3.36.2
Run-time dependency mutter-clutter-6 found: YES 3.36.2
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Program vapigen found: YES (/usr/bin/vapigen)
Program build-aux/meson/post_install.py found: YES (/media/sf_shared/Projekte/github.com/meisenzahl/gala/build-aux/meson/post_install.py)
Build targets in project: 19
WARNING: Project specifies a minimum meson_version '>= 0.48.0' but uses features which were added in newer versions:
 * 0.49.0: {'/ with string arguments'}

Found ninja-1.10.0 at /usr/bin/ninja
```

```
$ ninja -C build
ninja: Entering directory `build'
[6/78] Compiling Vala source ../lib/ActivatableComponent.vala ../.../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala.
../lib/Plugin.vala:89.9-89.38: warning: Type `Meta.Rectangle[]' can not be used for a GLib.Object property
        public Meta.Rectangle[] region { get; private set; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/Plugin.vala:96.9-96.49: warning: Type `Meta.Rectangle[]?' can not be used for a GLib.Object property
        protected Meta.Rectangle[]? custom_region {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/WindowManager.vala:67.9-67.50: warning: Type `Gala.KeybindingFilter?' can not be used for a GLib.Object property
        public KeybindingFilter? keybinding_filter { get; owned set; default = () => true; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 3 warning(s)
[10/78] Compiling Vala source ../src/DBus.vala ../src/DBusAcceler...lone.vala ../src/Widgets/WorkspaceInsertThumb.vala lib/gala.vapi.
FAILED: src/25a6634@@gala@exe/DBus.c src/25a6634@@gala@exe/DBusAccelerator.c src/25a6634@@gala@exe/DockThemeManager.c src/25a6634@@gala@exe/DragDropAction.c src/25a6634@@gala@exe/InternalUtils.c src/25a6634@@gala@exe/KeyboardManager.c src/25a6634@@gala@exe/NotificationStack.c src/25a6634@@gala@exe/Main.c src/25a6634@@gala@exe/MediaFeedback.c src/25a6634@@gala@exe/PluginManager.c src/25a6634@@gala@exe/ScreenSaverManager.c src/25a6634@@gala@exe/ScreenshotManager.c src/25a6634@@gala@exe/SessionManager.c src/25a6634@@gala@exe/Settings.c src/25a6634@@gala@exe/ShadowEffect.c src/25a6634@@gala@exe/WindowListener.c src/25a6634@@gala@exe/WindowManager.c src/25a6634@@gala@exe/WorkspaceManager.c src/25a6634@@gala@exe/Background/Animation.c src/25a6634@@gala@exe/Background/Background.c src/25a6634@@gala@exe/Background/BackgroundCache.c src/25a6634@@gala@exe/Background/BackgroundContainer.c src/25a6634@@gala@exe/Background/BackgroundManager.c src/25a6634@@gala@exe/Background/BackgroundSource.c src/25a6634@@gala@exe/Background/SystemBackground.c src/25a6634@@gala@exe/Widgets/IconGroup.c src/25a6634@@gala@exe/Widgets/IconGroupContainer.c src/25a6634@@gala@exe/Widgets/MonitorClone.c src/25a6634@@gala@exe/Widgets/MultitaskingView.c src/25a6634@@gala@exe/Widgets/PixelPicker.c src/25a6634@@gala@exe/Widgets/SafeWindowClone.c src/25a6634@@gala@exe/Widgets/ScreenShield.c src/25a6634@@gala@exe/Widgets/SelectionArea.c src/25a6634@@gala@exe/Widgets/WindowClone.c src/25a6634@@gala@exe/Widgets/WindowCloneContainer.c src/25a6634@@gala@exe/Widgets/WindowIconActor.c src/25a6634@@gala@exe/Widgets/WindowOverview.c src/25a6634@@gala@exe/Widgets/WindowSwitcher.c src/25a6634@@gala@exe/Widgets/WorkspaceClone.c src/25a6634@@gala@exe/Widgets/WorkspaceInsertThumb.c 
valac -C --debug --debug --target-glib=2.44 --hide-internal --enable-deprecated --vapidir=/media/sf_shared/Projekte/github.com/meisenzahl/gala/vapi --define HAS_MUTTER330 --define HAS_MUTTER332 --define HAS_MUTTER334 --define HAS_MUTTER336 /media/sf_shared/Projekte/github.com/meisenzahl/gala/vapi/config.vapi --pkg gnome-desktop-3.0 --pkg granite --pkg mutter-clutter-6 --pkg mutter-cogl-path-6 --pkg mutter-cogl-pango-6 --pkg mutter-cogl-6 --pkg libmutter-6 --pkg libbamf3 --pkg plank --pkg gdk-x11-3.0 --pkg gtk+-3.0 --pkg gee-0.8 --pkg gmodule-2.0 --pkg gio-2.0 --pkg gobject-2.0 --target-glib ' 2.44.0' --pkg glib-2.0 --color=always --directory src/25a6634@@gala@exe --basedir ../src ../src/DBus.vala ../src/DBusAccelerator.vala ../src/DockThemeManager.vala ../src/DragDropAction.vala ../src/InternalUtils.vala ../src/KeyboardManager.vala ../src/NotificationStack.vala ../src/Main.vala ../src/MediaFeedback.vala ../src/PluginManager.vala ../src/ScreenSaverManager.vala ../src/ScreenshotManager.vala ../src/SessionManager.vala ../src/Settings.vala ../src/ShadowEffect.vala ../src/WindowListener.vala ../src/WindowManager.vala ../src/WorkspaceManager.vala ../src/Background/Animation.vala ../src/Background/Background.vala ../src/Background/BackgroundCache.vala ../src/Background/BackgroundContainer.vala ../src/Background/BackgroundManager.vala ../src/Background/BackgroundSource.vala ../src/Background/SystemBackground.vala ../src/Widgets/IconGroup.vala ../src/Widgets/IconGroupContainer.vala ../src/Widgets/MonitorClone.vala ../src/Widgets/MultitaskingView.vala ../src/Widgets/PixelPicker.vala ../src/Widgets/SafeWindowClone.vala ../src/Widgets/ScreenShield.vala ../src/Widgets/SelectionArea.vala ../src/Widgets/WindowClone.vala ../src/Widgets/WindowCloneContainer.vala ../src/Widgets/WindowIconActor.vala ../src/Widgets/WindowOverview.vala ../src/Widgets/WindowSwitcher.vala ../src/Widgets/WorkspaceClone.vala ../src/Widgets/WorkspaceInsertThumb.vala lib/gala.vapi
../src/Background/Background.vala:186.33-186.36: warning: Argument 1: Cannot pass null to non-null parameter type
                        finish (null);
                                ^^^^
../src/Background/Background.vala:192.37-192.40: warning: Argument 1: Cannot pass null to non-null parameter type
                            finish (null);
                                    ^^^^
../src/Background/BackgroundSource.vala:123.17-123.34: error: The name `changed' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.changed.disconnect (background_changed);
                ^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundSource.vala:124.17-124.34: error: The name `destroy' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.destroy ();
                ^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundManager.vala:128.9-128.28: warning: Gala.BackgroundManager.set_size hides inherited method `Clutter.Actor.set_size'. Use the `new' keyword if hiding was intentional
        public void set_size (float width, float height) {
        ^^^^^^^^^^^^^^^^^^^^
../src/ShadowEffect.vala:121.13-122.59: warning: unhandled error `GLib.Error'
../src/Widgets/IconGroup.vala:543.17-543.27: warning: `null' incompatible with return type `Clutter.Actor'
                return null;
                ^^^^^^^^^^^
../src/DBus.vala:89.17-89.68: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                (wm.background_group as BackgroundContainer).changed.connect (() => background_changed ());
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 6 warning(s)
[15/78] Compiling C object 'lib/76b5a35@@gala@sha/meson-generated_WindowManager.c.o'.
ninja: build stopped: subcommand failed.
```

**Comment by meisenzahl** [comment]
@danrabbit @tintou @davidmhewitt Are you able to build `master` with daily-6.0?

**Comment by meisenzahl** [comment]
Does anyone have an idea how I can query sunrise and sunset via DBUS? `org.gnome.SettingsDaemon.Color` properties' `sunrise` and `sunset` always return `-1.0`

**Comment by danrabbit** [comment]
Hey @meisenzahl sorry for not following up here! After some discussion we decided to create a settings daemon for Pantheon. Could you move this functionality from a Gala PR to https://github.com/elementary/settings-daemon

**Pull request closed without merging**
