### PR TITLE
Restore unmaximize animation

### LINKED ISSUE #1185: Unmaximize effect not working with mutter >= 3.38
## What Happened

I build gala with mutter 3.38, everything is fine but unmaximize animation not working,

https://user-images.githubusercontent.com/33109339/126580695-6c8881e9-789d-43cc-9b5d-bc75c91e66cf.mp4

## Steps to Reproduce

1. Compile gala with mutter 3.38
2. Open a window and maximize
3. Unmaximize window

### Logs

```Dec 01 07:28:35 Archlinux gala[32496]: clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Dec 01 07:28:35 Archlinux gala[32496]: clutter_paint_volume_set_height: assertion 'height >= 0.0f' failed
Dec 01 07:28:36 Archlinux gala[32496]: invalid (NULL) pointer instance
Dec 01 07:28:36 Archlinux gala[32496]: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaStage>:0x55da5033dbf0] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55da5042ac80] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55da5042a320] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55da50dd9300] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55da50df5850] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaStage>:0x55da5033dbf0] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55da5042ac80] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55da5042a320] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55da50dd9300] is on because it needs an allocation.
Dec 01 07:28:39 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55da50df5850] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaStage>:0x55da5033dbf0] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55da5042ac80] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55da5042a320] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55da50dd9300] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55da50df5850] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaStage>:0x55da5033dbf0] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<ClutterActor>:0x55da5042ac80] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55da5042a320] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55da50dd9300] is on because it needs an allocation.
Dec 01 07:28:40 Archlinux gala[32496]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55da50df5850] is on because it needs an allocation.
```

## Platform Information

Distro: Archlinux
Version: Compiled from git
GPU: Mesa Intel® HD Graphics 530 (SKL GT2)

### PR DESCRIPTION
**Pull request by lenemter**
Resolves #1185.

### CODE REVIEW

**Comment by lenemter** [comment]
Noticed issues (probably need to be reported separably):
1. In OS 6 every window when unmaximized places inside of screen bounds. In OS 7 only Gtk apps do so, but when animation starts they report that they will be placed outside of display, which results in inaccurate animation. So as a workaround I manually place every window to where they report.

2. Inaccurate animation with some small windows (e.g. System Settings or Obliviate from AppCenter)
image
image

Occurs in both OS 6 and OS 7

3. Bounds of Gtk 4 windows with elementary stylesheet is broken.
elementary:
image
Adwaita:
image

Occurs in both OS 6 and OS 7

**Comment by TomiOhl** [comment]
Just noticed this in OS7, not opening an issue since probably this will fix it. Hope someone can review this soon, it's pretty annoying

**Comment by zeebok** [comment]
This looks fine. I am not super familiar with Gala's codease so I have no idea if I am missing something but at the very least I will test this tomorrow and approve if it looks alright.

**Review by zeebok — APPROVED** [review]

**Comment by lenemter** [comment]
When dock is always shown, some apps (like Files or Code) produce this glitch when you can see the window through dock for a few frames.

bug

I don't know what causes this and how to fix this. Any help will be appreciated.

**Pull request closed without merging**
