### PR TITLE
Cancel area screenshot when pressing esc

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixing: #311 
Using 2 signals to differentiate between captured and cancelled just like the [SelectionArea in Screenshot](https://github.com/elementary/screenshot/blob/master/src/Widgets/SelectionArea.vala).

### CODE REVIEW

**Comment by ricotz** [comment]
Have you try using an error to propagate the cancellation rather than setting and checking "invalid" values?

**Comment by peteruithoven** [comment]
I haven't, but I'd be basically guessing, I've been trying to find some api documentation of this `/org/gnome/Shell/Screenshot` / `org.gnome.Shell.Screenshot` interface.

This seems relevant: https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/data/dbus-interfaces/org.gnome.Shell.Screenshot.xml

This looks like the gnome shell implementation, where they indeed seem to use an IOError:
https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/screenshot.js#L169-183

This looks like the actual implementation of the screenshot part of the media keys plugin of the GNOME settings daemon:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/media-keys/gsd-screenshot-utils.c

It has this `if (!geometry)` check, but I'm not sure how it gets from the individual x, y, width, height to this one geometry value. 
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/media-keys/gsd-screenshot-utils.c#L223-228

**Comment by tintou** [comment]
@peteruithoven If you look at https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/data/dbus-interfaces/org.gnome.Shell.Screenshot.xml#L137 the SelectArea method has 4 out arguments, which is just represented by a GLib.Variant tuple: `(iiii)` → means `tuple-of(integer, integer, integer, integer)` so you can then get the result with `variant.get ("(iiii)", out x, out y, out width, out height)`

**Comment by tintou** [comment]
Vala allow you to do it even easier:
```vala
public struct ScreenshotGeometry {
    public int x;
    public int y;
    public int width;
    public int height;
}
…
// DBus method:
public async ScreenshotGeometry select_area () throws GLib.Error;
```

**Comment by peteruithoven** [comment]
@tintou Interesting, so that should be automatically possible because of how vala connects to these dbus interfaces? That has the potential to be more readable, I've tried the following (Ideally SelectionArea would have a `ScreenshotGeometry` property):
``` vala
public struct ScreenshotGeometry {
    public int x;
    public int y;
    public int width;
    public int height;
}

public async ScreenshotGeometry select_area () throws DBusError, IOError
{
  var selection_area = new SelectionArea (wm);
  selection_area.closed.connect (() => Idle.add (select_area.callback));
  wm.ui_group.add (selection_area);
  selection_area.start_selection ();

  yield;
  selection_area.destroy ();

  yield wait_stage_repaint ();
  int x;
  int y;
  int width;
  int height;
  selection_area.get_selection_rectangle (out x, out y, out width, out height);
  debug ("selection_rectangle: %ix%i %ix%i", x, y, width, height);
  return ScreenshotGeometry() {
    x = x,
    y = y,
    width = width,
    height = height
  }
}
```
But, while the logged `selection_rectangle` seemed valid it's not picked up properly:
```
* (gala:19137): DEBUG: 13:12:56.032: ScreenshotManager.vala:155: selection_rectangle: 2313x620 1393x906
** (gala:19137): DEBUG: 13:12:56.034: ScreenshotManager.vala:88: Taking area screenshot
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

** (gala:19137): DEBUG: 13:12:56.053: ScreenshotManager.vala:43: Flashing area

(gala:19137): Gdk-CRITICAL **: 13:12:56.054: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(gala:19137): GdkPixbuf-CRITICAL **: 13:12:56.054: gdk_pixbuf_save_to_stream_async: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```

**Comment by ricotz** [comment]
If an error is set then nothing is assigned and NULL is returned. So the code is fine as it is now.

Whether a restructuring by using a struct for optimizations makes sense is out of scope of that merge.

**Pull request merged**
