### PR TITLE
Fix multitasking view animations

### PR DESCRIPTION
**Pull request by lenemter**
- Fix weird icon animation when opening multitasking view
- Animate maximized windows shadow opacity with gestures

### CODE REVIEW

**Comment by peteruithoven** [comment]
Could you clarify which shadow opacity animation you're referring to?

**Comment by lenemter** [comment]
@peteruithoven This PR animates the shadow opacity when opening multitasking view with gestures. In `master` when opening/closing multitasking view with gestures shadow suddenly appears/disappears when you end the gesture.

**Comment by peteruithoven** [comment]
I think I might have captured that shadow issue in the following capture? 
[Gala master shadow issue.webm](https://user-images.githubusercontent.com/523210/219873672-5f56bc8d-c5e5-49a6-a7ab-e08b95c21902.webm)

**Comment by lenemter** [comment]
@peteruithoven No, that is different bug that has been fixed in #1531. There is an update planned forward the end of February, so you need to wait for the fix :)

**Review by danirabbit — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
