### PR TITLE
Fix panel sometimes being behind windows

### LINKED ISSUE #2080: Dock flickering
### What Happened?

Dock sometimes gets in "flickering" mode when using an app in full screen. When moving the cursor to the bottom of the screen it appears shortly and immediately disappears so you can't click an icon anymore.

### Steps to Reproduce

Hard to reproduce. It appears with apps in full screen mode (Firefox f.e.), but not always.

1. Open an app in full screen mode (f.e. Firefox).
2. Try to use the dock (it may be in "flickering mode")
3. You can stop the flickering mode by enabling the application menu once, f.e.

### Expected Behavior

Dock should always appear smoothly and stay to await my clicks.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

Thinkpad X280
Wayland session, 1.25x scale, i915 graphics driver.

### PR DESCRIPTION
**Pull request by leolost2605**
Fixes #2080

### CODE REVIEW

**Review by lenemter — CHANGES_REQUESTED** [review]
This fixes the issue with the Dock, but not if you log in -> open maximized window using Super + number -> press Super to open Applications menu, this results in application menu being below maximized window. I guess we need to apply the same fix somewhere else in the code?

**Comment by leolost2605** [comment]
Yeah probably I'm just not sure where would be best. I guess we should connect to some event but which? We could do focus on the window but that only works because we know the wingpanel implementation and that it requests focus every time it goes out of it's reserved space :shrug:
Any ideas?

**Comment by lenemter** [comment]
I have no idea either. I think we should add // FIXME here and just merge it. We can fix wingpanel issue later as it's not critical.

**Comment by TomiOhl** [comment]
Note that even on "stock" Horus (and nothing compiled from source) the application menu is behind maximized windows, so it's not a new issue and not related to new changes

**Comment by leolost2605** [comment]
> I have no idea either. I think we should add // FIXME here and just merge it. We can fix wingpanel issue later as it's not critical.

I did that now so it updates visible on focused which should fix the wingpanel issue for now

**Comment by TomiOhl** [comment]
> > Note that even on "stock" Horus (and nothing compiled from source) the application menu is behind maximized windows, so it's not a new issue and not related to new changes
> 
> Hmm I don't remember that. Maybe you mean fullscreen windows so that wingpanel isn't visible at all?

Oh yes I mean fullscreen, when wingpanel isn't visible. Then if I press Super + space to open the application menu, it opens behind the window (I can search and launch apps via the keyboard). Doesn't happen if the app is just maximized and wingpanel is still visible, in that case the application menu appears above the window. Got a little confused by the terms, sorry

**Review by lenemter — APPROVED** [review]

**Pull request merged**
