### PR TITLE
Auto-move maximized windows by default

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by andreasfelix** [comment]
This will introduce some regressions on multi-monitor setups: 
- The workspace on the primary monitor changes, if one maximizes a window on a secondary monitor.
- The workspace on the primary monitor changes, if one un-maximizes a window on a secondary monitor, even if the workspace is non-empty.

**Comment by danrabbit** [comment]
@andreasfelix are these filed issues? If not, can make sure they are? It would be good to make sure we're tracking these

**Comment by andreasfelix** [comment]
done (see #886)

**Comment by andreasfelix** [comment]
> This will introduce some regressions on multi-monitor setups:
> 
> * The workspace on the primary monitor changes, if one maximizes a window on a secondary monitor.
> * The workspace on the primary monitor changes, if one un-maximizes a window on a secondary monitor, even if the workspace is non-empty.

This should be fixed by #1033

**Comment by danrabbit** [comment]
Yeah I'm going to close this. For some multi-window workflows it's kind of annoying.

**Pull request closed without merging**
