### PR TITLE
Allow focusing a window via DesktopIntegration

### PR DESCRIPTION
**Pull request by leolost2605**
Adds a dbus method that focuses the window with the given uid.
Is there a better way to find a window by uid instead of iterating over all windows (I'm not too familiar with gala/mutter methods)?

Goes with elementary/dock#196

### CODE REVIEW

**Comment by danirabbit** [comment]
I haven't tested this yet but just wanna reference #1377 which was the design we were looking at based on survey results

**Comment by leolost2605** [comment]
Would a window list with window titles in the context menu still be part of the design? I think for this and for cycling through windows by scrolling over the icon, this method here would still be useful. Also since we now have the DesktopIntegration we know quite a lot about the windows of applications so I wonder whether that was a limiting factor for the design?
Or should the window spread be the only way to cycle through windows?

**Comment by leolost2605** [comment]
@danirabbit should we go forward on this? Or drop the window list from the context menu entirely? I personally don't use it but it's not a lot to maintain so we might as well keep it 🤷

**Review by lenemter — APPROVED** [review]

**Comment by danirabbit** [comment]
@leolost2605 sorry for taking so long to follow up on this. I believe the scrolling behavior is at least a somewhat popular feature so that makes sense to keep imo. I think I'd rather hold off on adding a list of windows to the menu until we get some feedback that indicates this is a useful feature for people. The feedback we've received in the past about people wanting to see a preview of the actual window in order to choose leads me to believe that the list isn't useful

**Pull request merged**
