### PR TITLE
Add support for Mutter 42

### LINKED ISSUE #1367: add support for mutter 42 / `libmutter-10`
GNOME has released mutter 42-alpha, and as usual, this broke some things.

The library name has been changed from `libmutter-9` to `libmutter-10`, but other than that, the API differences don't look *too bad* this time (knocks on wood), possibly incomplete list of changes (collected from libmutter header diffs):

## mutter-clutter

changed:

- `clutter_stage_update_device`: added `cairo_region_t region` argument

added:

- `ClutterActor`: addition of `clutter_actor_add_action_full` method
- `ClutterTouchpadHoldEvent`: new
- `clutter_context_{new,free}`: new
- `clutter_pick_context_log_overlap`: new

removed:

- `CallyActorClass`: removal of `focus_clutter` signal handler
- `ClutterBoxLayout`: removal of `clutter_box_layout_{get,set}_pack_start`
- `ClutterContainer` removal of `raise`, `lower`, `sort_depth_order` signal handlers
- `ClutterZoomAxis`: removed
- `clutter_zoom_action_{get,set}_zoom_axis`: removed
- `ClutterEvent`: removed `clutter_event_get_click_count`
- `clutter{_base}_init`: removed
- `clutter_get_option_group{_without_init}`: removed
- `clutter_get_default_frame_rate`: removed
- `clutter_set_custom_backend_func`: removed
- `ClutterPanAction`: removed `pan` method
- `ClutterRotateAction`: removed `rotate` method
- `ClutterSwipeAction`: removed `swipe` method
- `ClutterZoomAction`: removed `zoom` method

removed deprecated:

- `ClutterContainer`: removed `clutter_container_get_children`, `clutter_container_raise_child`, `clutter_container_lower_child`, `clutter_container_sort_depth_order` methods

## mutter-cogl

added:

- `CoglOnscreen`: new `queue_damage_region` method
- `MetaDisplay`: new `meta_display_list_all_windows` method
- `MetaBackend`: new `meta_backend_get_monitor_manager` method
- `MetaBackend`: new `meta_backend_is_headless` method
- `meta_get_clutter_debug_flags`: new
- `MetaWindow` new `meta_window_has_attached_dialogs` method

removed:

- `cogl_framebuffer_draw_primitive`: removed

removed deprecated:

- `cogl_{get,set}_depth_test_enabled`: removed
- `cogl_{get,set}_backface_culling_enabled`: removed
- `cogl_texture_new_with_size`: removed
- `cogl_texture_new_from_sub_texture`: removed

### PR DESCRIPTION
**Pull request by tintou**
Closes #1367

### CODE REVIEW

**Comment by decathorpe** [comment]
This compiles fine on Fedora Rawhide with mutter 42-alpha! :tada: 👍🏼 

I'm getting a few warnings (particularly the last one seems to indicate a logic bug), but they aren't caused by this PR, as far as I can tell.

```
../lib/DragDropAction.vala:254.13-254.38: warning: Switch does not handle `BUTTON_PRESS', `PAD_STRIP', `TOUCH_BEGIN', `TOUCH_CANCEL', `TOUCHPAD_HOLD', `IM_COMMIT', `NOTHING', `PAD_BUTTON_PRESS', `EVENT_LAST', `PAD_RING', `TOUCH_UPDATE', `DEVICE_ADDED', `TOUCHPAD_PINCH', `PROXIMITY_IN', `IM_DELETE', `KEY_RELEASE', `PAD_BUTTON_RELEASE', `SCROLL', `TOUCH_END', `TOUCHPAD_SWIPE', `DEVICE_REMOVED', `PROXIMITY_OUT', `IM_PREEDIT' of enum `Clutter.EventType'
  254 |             switch (event.get_type ()) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~  
../lib/Plugin.vala:89.9-89.38: warning: Type `Meta.Rectangle[]' can not be used for a GLib.Object property
   89 |         public Meta.Rectangle[] region { get; private set; }
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      
../lib/Plugin.vala:96.9-96.49: warning: Type `Meta.Rectangle[]?' can not be used for a GLib.Object property
   96 |         protected Meta.Rectangle[]? custom_region {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
../lib/WindowManager.vala:69.9-69.50: warning: Type `Gala.KeybindingFilter?' can not be used for a GLib.Object property
   69 |         public KeybindingFilter? keybinding_filter { get; owned set; default = () => true; }
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          
Compilation succeeded - 4 warning(s)
```

```
../src/ScreenshotManager.vala:358.17-365.17: warning: unhandled error `GLib.Error'
  358 |                 wm.stage.paint_to_buffer (
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
  359 |                     {x, y, width, height},
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  360 |                     scale,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~
  361 |                     image.get_data (),
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  362 |                     image.get_stride (),
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  363 |                     Cogl.PixelFormat.BGRA_8888_PRE,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  364 |                     paint_flags
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  365 |                 );
      | ~~~~~~~~~~~~~~~~~ 
../src/ScreenshotManager.vala:367.17-374.17: warning: unhandled error `GLib.Error'
  367 |                 wm.stage.paint_to_buffer (
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
  368 |                     {x, y, width, height},
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  369 |                     scale,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~
  370 |                     image.get_data (),
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  371 |                     image.get_stride (),
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  372 |                     Cogl.PixelFormat.ARGB_8888_PRE,
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  373 |                     paint_flags
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  374 |                 );
      | ~~~~~~~~~~~~~~~~~ 
../src/Background/BackgroundManager.vala:125.9-125.28: warning: Gala.BackgroundManager.set_size hides inherited method `Clutter.Actor.set_size'. Use the `new' keyword if hiding was intentional
  125 |         public void set_size (float width, float height) {
      |         ^~~~~~~~~~~~~~~~~~~~                              
../src/Widgets/WorkspaceInsertThumb.vala:81.9-81.22: warning: Gala.WorkspaceInsertThumb.transform hides inherited method `Clutter.Actor.transform'. Use the `new' keyword if hiding was intentional
   81 |         void transform (bool expand) {
      |         ^~~~~~~~~~~~~~                
../src/Widgets/MultitaskingView.vala:289.85-289.103: note: Assignment: Unsafe conversion from `int' to `Gala.AnimationDuration'
  289 |                 var duration = is_nudge_animation ? (AnimationDuration.NUDGE / 2) : calculated_duration;
      |                                                                                     ^~~~~~~~~~~~~~~~~~~ 
../src/PluginManager.vala:141.13-141.29: warning: Switch does not handle `ADDITION' of enum `Gala.PluginFunction'
  141 |             switch (provides) {
      |             ^~~~~~~~~~~~~~~~~  
../src/Widgets/WindowCloneContainer.vala:230.17-230.34: warning: Switch does not handle `DOWN_RIGHT', `UP_RIGHT', `DOWN_LEFT', `UP_LEFT' of enum `Meta.MotionDirection'
  230 |                 switch (direction) {
      |                 ^~~~~~~~~~~~~~~~~~  
../src/PluginManager.vala:34.9-34.37: warning: Type `X.Xrectangle[]' can not be used for a GLib.Object property
   34 |         public X.Xrectangle[] regions { get; private set; }
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      
Compilation succeeded - 7 warning(s)
```

Particularly this one looks like an error:

```
src/gala.p/WindowManager.c: In function ‘gala_window_manager_gala_real_plugin_info’:
src/gala.p/WindowManager.c:8846:16: warning: function returns address of local variable [-Wreturn-local-addr]
 8846 |         return result;
      |                ^
src/gala.p/WindowManager.c:8841:24: note: declared here
 8841 |         MetaPluginInfo _tmp0_;
      |                        ^
```

**Review by decathorpe — APPROVED** [review]

**Comment by decathorpe** [comment]
Weird. This builds correctly on Rawhide and Fedora 34 (which is what I tested), but not on Fedora 35.

Looks like somehow both mutter-cogl-9.vapi and mutter-cogl-10.vapi end up being included, there's lots of errors like this one:

```
mutter-cogl-9.vapi:1525.2-1525.49: error: `Cogl' already contains a definition for `x11_onscreen_get_window_xid'
	public static uint32 x11_onscreen_get_window_xid (Cogl.Onscreen onscreen);
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mutter-cogl-10.vapi:1525.2-1525.49: note: previous definition of `x11_onscreen_get_window_xid' was here
	public static uint32 x11_onscreen_get_window_xid (Cogl.Onscreen onscreen);
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The same error happens in greeter and wingpanel on Fedora 35. Is one of the symlinks / includes in the .vapi files wrong?

**Comment by pimvullers** [comment]
Same errors appear on Gentoo after adding this patch to latest gala release

**Comment by pimvullers** [comment]
OK, found that commit e7d1682cf68e642883d07a4fa5e3c99aaa4046a0 resolves this. Thanks, Gentoo package has been updated accordingly.

**Pull request merged**
