### PR TITLE
Regenerate the vapi using the .metadata files

### PR DESCRIPTION
**Pull request by tintou**
We are now sure that we have the right symbols available with the right version

### CODE REVIEW

**Comment by tintou** [comment]
@worldofpeace can you see if that fixes #637

**Comment by worldofpeace** [comment]
> @worldofpeace can you see if that fixes #637

Sure, will check :+1:

**Comment by worldofpeace** [comment]
Ok, compilation fails on NixOS Gnome 3.34 with these regenerated vapi's
* https://gist.github.com/worldofpeace/c4d7f2afc0d00faee3d9ee4987db1926

lots with `error: too few arguments to function 'g_boxed_free'`.

@tintou What do you think about having a never ubuntu target in CI for the mutter using projects?
Just think it would make things easier to test against multiple mutter versions.

**Comment by tintou** [comment]
@worldofpeace it looks like an issue with Vala, can you try with Vala master to see if it has been fixed and otherwise open a bug there? I think that I was using latest Vala to build it here

**Comment by worldofpeace** [comment]
> @worldofpeace it looks like an issue with Vala, can you try with Vala master to see if it has been fixed and otherwise open a bug there? I think that I was using latest Vala to build it here

I suspected similar, will try.

**Comment by worldofpeace** [comment]
Thanks, works :+1: 

Screenshot from 2019-11-22 03-34-57

Tested overview mode also.

**Pull request merged**
