### PR TITLE
Multi-touch gestures aren't pixel-precise at low speeds + D-Bus

### LINKED ISSUE #1016: Multi-touch gestures aren't pixel-precise at low speeds
## What Happened
This is less of a bug and more of unwanted behavior. Touchegg gestures track fingers really well but the animations are choppy/jumpy. When you move your fingers slowly, you can see each animation "frame" jumps about 10px in size. Maybe there is a performance reason for this, but I hoping we could reduce the amount of pixels each "frame" moves.

## Expected Behavior

I took a look at my wife's macbook. The animations are a bit smoother with each "jump" being only a pixel or two.

### Logs

No logs to show but can be shown if requested. I imagine this is less of a "my machine" thing. 

## Platform Information

Manjaro Gnome with a pantheon session.

### Demo
The gif below will show what I am talking about. You can see when i move my fingers consistently, the animation looks pretty smooth. However, if I slow down, you can begin to see how large each jump is. 

Screen Capture_select-area_20210113103841-min

### PR DESCRIPTION
**Pull request by JoseExposito**
Fix #1016 and https://github.com/elementary/gala/issues/990

Requires the changes introduced in the daemon here: https://github.com/JoseExposito/touchegg/issues/434 & https://github.com/JoseExposito/touchegg/issues/436

Merging this will need some synchronization releasing the daemon, just ping me on Slack before merging this.

### CODE REVIEW

**Review by danrabbit — DISMISSED** [review]
I can confirm this works as expected with the latest Touchégg master. So we just are blocked until the next upstream release :)

**Comment by JoseExposito** [comment]
As I mentioned in Slack, I was working on D-Bus support. Since this branch is already blocked and the migration to D-Bus also uses a `double` for gesture percentage, it didn't make sense to create a different PR.

I followed @tintou's [implementation](https://github.com/elementary/applications-menu/blob/master/src/synapse-plugins/switchboard-plugin/plugin.vala), in case you want to follow that for the review. He also helped me with a bug I wasn't able to find, so thanks a lot! :smile: 

I tried to follow @meisenzahl's [advice](https://github.com/elementary/gala/issues/990#issuecomment-766308634) but I wasn't able to use an interface as he suggested over Unix socket. I don't know if it is possible, but I wasn't able to find a way.
I have 0 experience with D-Bus, so I appreciate every comment you can make to improve the code.

**Comment by JoseExposito** [comment]
I'll release a new Touchégg version in 1 or 2 days. I think it is safe to do so as the package should be generated from os-patches and not from upstream, but I just wanted to make sure this is the case to avoid breaking Gala gestures :smile:

**Comment by danrabbit** [comment]
@JoseExposito it won't break anything as I'm manually pulling in release snapshots :)

**Review by danrabbit — APPROVED** [review]
Extremely smooth. Nice work!

**Comment by andrewc910** [comment]
Working great on my XPS 9560. Thank you @JoseExposito

**Pull request merged**
