### PR TITLE
MultitaskingView: Add blurred wallpaper

### PR DESCRIPTION
**Pull request by lenemter**
Fixes https://github.com/elementary/gala/issues/1796

### CODE REVIEW

**Comment by danirabbit** [comment]
Very cool! Is there a reason we didn't use the Clutter blur effect and implemented our own?

I submitted a branch here to add a brightness effect for some extra contrast, thoughts? https://github.com/elementary/gala/pull/1811

I'm getting a consistent crash on logging into the session and entering the multitasking view. If I switch workspaces first it doesn't crash

**Comment by lenemter** [comment]
> Very cool! Is there a reason we didn't use the Clutter blur effect and implemented our own?

I think it uses a simple shader with a small blur radius and there's no way to change it.

> I'm getting a consistent crash on logging into the session and entering the multitasking view. If I switch workspaces first it doesn't crash

Can you provide the backtrace please? It doesn't crash on my side.

**Comment by lenemter** [comment]
@danirabbit I actually found a typo I made that made it crash with certain blur radius. I hope it fixes the crash for you too

**Review by danirabbit — APPROVED** [review]
LFG!

**Pull request merged**
