### PR TITLE
Don't remove workspaces on switching in multitasking view

### LINKED ISSUE #277: Don't remove empty workspaces when in workspace view
Automatically removing empty workspaces results in a few bad things:
* you can't freely rearrage apps how you want because as soon as you move only app from a workspace and switch to another it gets deleted
* you can't "swap" apps for their workspaces: say I want to move app A to workspace B, and app B to workspace A, this isn't possible since as soon as you switch to workspace B, workspace A is deleted
* it causes unnecessary animation shift in the view itself

Empty workspaces should be cleaned up when the user actually quits the workspace view.

### PR DESCRIPTION
**Pull request by donadigo**
Fixes #277.

Prevents from aggressive removing of workspaces when switching between them in the multitasking view.
All empty workspaces get cleaned up when the multitasking view is closed except active one, so if the user enters a non-last empty workspace, it doesn't get removed.

### CODE REVIEW

**Comment by donadigo** [comment]
Now ready to review.

**Comment by donadigo** [comment]
Ready to review again.

**Comment by jeremypw** [comment]
@donadigo Converting to draft as has conflicts, unaddressed issues and no recent activity.  Please feel free to close or reopen for review after fixing conflicts as desired.

**Comment by danirabbit** [comment]
Gonna close since this hasn't had movement in a couple years and conflicts with the current codebase

**Pull request closed without merging**
