### PR TITLE
WindowClone: Layout in allocate virtual

### LINKED ISSUE #2088: Invisible window clones
Since #2072 some WindowClones are not visible (for me it's especially xwayland clients e.g. vs code). 
The issue temporarily fixed by #2072 is probably more severe (it can lead to everything breaking enough so that you have to restart gala and thus the session from a different tty) so I wouldn't revert for now.
But the root cause for that will be fixed in #2082 and thus that also reverts #2072 and fixes this issue.

### LINKED ISSUE #2128: Multitasking view does not show the application windows, only the icon
### What Happened?

In **classic session**, the multitasking view does not show the application windows, only the icon.

Classic session
Captura de tela de 2024-11-29 09 22 27

the same does not happen in **safe session**
Captura de tela de 2024-11-29 09 25 11

### Steps to Reproduce

1. in the dock, click on multitasking view
2. the multitasking view will show open applications
3. only the icons will appear

### Expected Behavior

Multitasking view should show the window image and the application icon.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

notebook Asus i5 8gb ram Intel HD Graphics 4000
monitor resolution 1366x768

### PR DESCRIPTION
**Pull request by leolost2605**
Currently we are doing most of the layout management by hardcoding x, y, width and height of our child actors. However we can make the whole thing simpler and more robust by doing the layout management in the allocate virtual method as recommended by clutter docs.

Since the root cause for the following issues was that we didn't allocate some children on rare occasions which was fixed in this PR this
fixes https://github.com/elementary/gala/issues/2053 and
fixes https://github.com/elementary/gala/issues/1898 and therefore
closes #2072 

There are still some issues when windows spawn while multitasking view is open (like for example they reserve space but don't show) that I would like to tackle in follow up PRs but at least it doesn't completely break anymore as on current main :)

fixes #2088 by reverting #2072

Fixes #2128

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
I can confirm that this fixes the linked issues, but it looks like the textures (window clones, close buttons, app icons) are all rendered half a pixel offset so they're blurry (this is on LoDPI and Wayland)

**Comment by danirabbit** [comment]
Tooltips also appear to be cut off and text looks pretty gnarly. Although when I went back to get a screenshot the other textures all look aligned correctly here :thinking: 

This branch:
Screenshot from 2024-10-11 10 47 41

main:
Screenshot from 2024-10-11 10 48 45

**Comment by leolost2605** [comment]
@danirabbit the allocations are clamped to pixels now could you try again with that? I'm not so good at noticing those differences :sweat_smile: 
(and the tooltip thing I don't seem to be able to reproduce, probably requires a very specific window size and name :shrug:)

**Comment by leolost2605** [comment]
So fedora is failing because for some reason it compiles with stricter rules (?) about implicit function declaration and `clutter_actor_get_relative_transformation_matrix` is defined in `clutter-mutter.h` and not `clutter.h` which we don't include anywhere. At least that's what I figured maybe I'm wrong somewhere :)

**Comment by leolost2605** [comment]
Nvm I found a utility method that's much better to use in this case and properly exported :)

**Comment by lenemter** [comment]
@leolost2605 Is this ready for review? I really want to include this in 8.0.4 release.

One thing I noticed is that clone no longer has magnifying filters? `clone.set_content_scaling_filters (Clutter.ScalingFilter.TRILINEAR, Clutter.ScalingFilter.TRILINEAR);` seems to fix this.

**Comment by leolost2605** [comment]
@lenemter yes it's ready.

I've added the filters although TBH i don't really know what they do :sweat_smile:

**Comment by tintou** [comment]
Opened https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4156 for your missing includes…

**Comment by leolost2605** [comment]
Thank you!

**Review by lenemter — CHANGES_REQUESTED** [review]
Looks great, one small issue in the code, after that should be ready to go

**Review by lenemter — APPROVED** [review]

**Comment by lenemter** [comment]
@danirabbit Can you review this branch please?

**Review by danirabbit — CHANGES_REQUESTED** [review]
Everything looks sharp but it looks like this re-introduces the issue where windows that spawn while multitasking view is open aren't added. To reproduce:

1. Open screenshot and set a timed screenshot
2. Open multitasking view
3. when the timer runs out the new window will be transparent with no icon tooltip etc

**Comment by leolost2605** [comment]
> There are still some issues when windows spawn while multitasking view is open (like for example they reserve space but don't show) that I would like to tackle in follow up PRs but at least it doesn't completely break anymore as on current main :)

From the description (the breaking refers to the version before the workaround was merged)

If it's a must I can do it here though :shrug:

**Review by danirabbit — APPROVED** [review]
Ah sorry I missed that. In that case 👍 😀

**Pull request merged**
