### PR TITLE
Daemon: Implement monitor labels

### LINKED ISSUE #1823: API for display labels
### Problem

In System Settings we have colored display labels that we set while the display configuration page is open. However we won't be able to position those windows in GTK 4/Wayland

### Proposal

Some kind of API either to position those windows as with the Dock and Panel

OR

Draw these labels in Gala and a simple API to show/hide them

### Prior Art (Optional)

https://github.com/elementary/switchboard-plug-display/blob/master/src/Widgets/DisplayWindow.vala

### PR DESCRIPTION
**Pull request by leolost2605**
Taken from #1840 (was easier than rebase :))

Fixes #1823 

For the switchboard side see elementary/switchboard-plug-display#372

### CODE REVIEW

**Comment by lenemter** [comment]
I'm not sure if window title is a good way to do this. I remember https://github.com/elementary/gala/pull/1427 was rejected for this reason. @tintou how should gala identify gala-daemon windows?

**Comment by leolost2605** [comment]
Yeah I wasn't sure either but I think the difference to #1427 is that we already know for sure that it's a daemon window and only differentiate between different types of daemon windows 🤷

**Comment by tintou** [comment]
Note that `handle_daemon_window` won't be called on X11 so we need another wrapper for X11, maybe by just ensuring that `("%" + uint64.FORMAT).format (window.get_pid ()) == subprocess.get_identifier ()`.
I think that this is good enough for a first iteration, ideally the daemon should communicate each type of window with a dedicated DBus signal, but that would probably be better to iterate on it so that we can move faster.

**Comment by leolost2605** [comment]
Since the daemon is still GTK3 I've just used the GTK3 methods for positioning etc. for X11

**Review by tintou — APPROVED** [review]

**Pull request merged**
