### PR TITLE
Track all windows

### PR DESCRIPTION
**Pull request by vjr**
Track positions of all windows using `Meta.Window.get_id ()` to uniquely identify.

Tested with Firefox which has option to restore windows upon launch.

### CODE REVIEW

**Comment by vjr** [comment]
Not sure if this is right, need to compare this PR vs stock gala.

**Comment by lenemter** [comment]
I think `Meta.Window.get_id ()` returns unique window id and gala can't rely on it to track window in any way?

**Comment by vjr** [comment]
> I think `Meta.Window.get_id ()` returns unique window id and gala can't rely on it to track window in any way?

I was looking for a way to ID the windows across sessions so that they all could be restored to their last positions, but I guess it might not be feasible. Your PR should be just fine whatever is the final code that gets merged, I appreciate it :-)

**Comment by vjr** [comment]
Closing since the main PR covers everything.

**Pull request closed without merging**
