### PR TITLE
Supposedly fix the issue with server side context menus

### LINKED ISSUE #174: Header context menu on not-native apps
In native apps we can open header context menu with some useful options like "Always on top". But with another apps we can't. Looks like this is only for GTK3 apps. But I remember that earlier, in previous version of elementary, we can do it with any app.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/55059896-header-context-menu-on-not-native-apps?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by donadigo**
Fixes #174.
It happens so that if we enter modal mode and add an Idle callback, the thing starts to work on server side decorations.

### CODE REVIEW

**Comment by jlnr** [comment]
I've been running this branch for an hour now and I'm seeing a weird glitch where I invoke the window menu on the same window several times, and the menus has different contents - it alternates between the shorter menu where "[x] Show on all workspaces" is checked, and then it goes back to the one where this is unchecked, and where the menu items for "Move to next/previous workspace" are available.

It might be an unrelated glitch, but I've never seen this behavior before.

**Comment by donadigo** [comment]
@jlnr yes, I've also experienced this and tbh I think it does exist in master but I have still to confirm it. This branch didn't touch any of the daemon that handles the menu, just invoking it to show, so the issue is probably in the daemon.

**Comment by Djaler** [comment]
Doesn't work for me :C

**Comment by danrabbit** [comment]
Superseded by #429

**Pull request closed without merging**
