### PR TITLE
Hardcode accent colors

### PR DESCRIPTION
**Pull request by lenemter**

### CODE REVIEW

**Comment by danirabbit** [comment]
Instead of hardcoding accent colors, can we get the RGB value directly over the settings portal?

Screenshot from 2023-06-13 11 36 35

**Comment by lenemter** [comment]
@danirabbit I think we can get only color of the currently applied accent color, not all of them.

**Comment by danirabbit** [comment]
Oh okay, I see what this is about. This is for setting the accent color based on the wallpaper. Sorry for the confusion! Makes sense

**Review by danirabbit — APPROVED** [review]
Works as expected. Nice job! :)

**Pull request merged**
