### PR TITLE
Add "Switch windows" gesture

### PR DESCRIPTION
**Pull request by lenemter**
Fixes https://github.com/elementary/gala/issues/1317
Fixes https://github.com/elementary/gala/issues/979

### CODE REVIEW

**Review by danirabbit — COMMENTED** [review]
This works for me! Is there a reason that only swiping to the right works? Can we initiate the switch when swiping either direction?

**Comment by lenemter** [comment]
> Is there a reason that only swiping to the right works? Can we initiate the switch when swiping either direction?

This is a limitation of our current gesture system and I have no idea how to avoid it. So basically gesture have a direction and a progress. If you initiate swipe to left, you cannot change your mind and swipe to the right to select different windows. Which might be unexpected so I removed it. You can see how it worked in [00920b6](https://github.com/elementary/gala/pull/1802/commits/00920b6e18cb5745950609bbbac0987b1e786b75).

**Comment by TomiOhl** [comment]
Not sure if this is any help, but currently this can be done via touchégg [like this](https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys:~:text=Example%202%3A%20Switch%20between%20windows%20(Alt%2BTab)). Probably it's different as it's a repeated gesture instead of a long continuous one.
Maybe there is a way to cancel the gesture when the direction changes and start one to the opposite direction?

**Comment by lenemter** [comment]
I decided to allow swiping to the left, but you cannot jump to the start of the window list from the end, which hides the flaw of the gesture system and emulates Windows 10 gestures behaviour.

**Review by danirabbit — APPROVED** [review]
Works perfectly, great job :)

**Pull request merged**
