### PR TITLE
Fix crash when using tiling shortcuts

### PR DESCRIPTION
**Pull request by lenemter**
Fixes this crash:

```
#0  0x00007757d433eba0 n/a (libmutter-clutter-14.so.0 + 0x36ba0)
#1  0x00007757d433d365 n/a (libmutter-clutter-14.so.0 + 0x35365)
#2  0x00007757d433ba79 n/a (libmutter-clutter-14.so.0 + 0x33a79)
#3  0x00007757d433cfa5 n/a (libmutter-clutter-14.so.0 + 0x34fa5)
#4  0x00007757d433d21e n/a (libmutter-clutter-14.so.0 + 0x3521e)
#5  0x00007757d53db6bd n/a (libgobject-2.0.so.0 + 0x356bd)
#6  0x00007757d53db7c1 g_signal_emit_valist (libgobject-2.0.so.0 + 0x357c1)
#7  0x00007757d53db883 g_signal_emit (libgobject-2.0.so.0 + 0x35883)
#8  0x00007757d433ee07 clutter_actor_show (libmutter-clutter-14.so.0 + 0x36e07)
#9  0x00007757d434ac38 clutter_actor_add_child (libmutter-clutter-14.so.0 + 0x42c38)
#10 0x00005addc428075b gala_window_manager_gala_unmaximize (gala + 0x6e75b)
#11 0x00005addc427b894 gala_window_manager_gala_real_size_changed (gala + 0x69894)
#12 0x00007757d44f15e1 n/a (libmutter-14.so.0 + 0xf15e1)
#13 0x00007757d456c3c2 n/a (libmutter-14.so.0 + 0x16c3c2)
#14 0x00007757d456c688 n/a (libmutter-14.so.0 + 0x16c688)
#15 0x00007757d4561c7b n/a (libmutter-14.so.0 + 0x161c7b)
#16 0x00007757d456762d n/a (libmutter-14.so.0 + 0x16762d)
#17 0x00007757d455f746 n/a (libmutter-14.so.0 + 0x15f746)
#18 0x00007757d3c6fb16 n/a (libffi.so.8 + 0x7b16)
#19 0x00007757d3c6c3ef n/a (libffi.so.8 + 0x43ef)
#20 0x00007757d3c6f0be ffi_call (libffi.so.8 + 0x70be)
#21 0x00007757d4fd2393 n/a (libwayland-server.so.0 + 0x9393)
#22 0x00007757d4fd6bb4 n/a (libwayland-server.so.0 + 0xdbb4)
#23 0x00007757d4fd5402 wl_event_loop_dispatch (libwayland-server.so.0 + 0xc402)
#24 0x00007757d45442ab n/a (libmutter-14.so.0 + 0x1442ab)
#25 0x00007757d54665b5 n/a (libglib-2.0.so.0 + 0x5d5b5)
#26 0x00007757d54c5717 n/a (libglib-2.0.so.0 + 0xbc717)
#27 0x00007757d5466f77 g_main_loop_run (libglib-2.0.so.0 + 0x5df77)
#28 0x00007757d44d50da meta_context_run_main_loop (libmutter-14.so.0 + 0xd50da)
#29 0x00005addc4255df1 gala_main (gala + 0x43df1)
#30 0x00005addc4255fdc main (gala + 0x43fdc)
#31 0x00007757d3a2a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)
#32 0x00007757d3a2a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)
#33 0x00005addc423c8b5 _start (gala + 0x2a8b5)
```

### CODE REVIEW

**Comment by danirabbit** [comment]
Do you have reproduction steps for this? Changes make sense, but I can't reproduce a tiling crash

**Comment by lenemter** [comment]
I still can reproduce the crash by rapidly tiling a window using Super + Ctrl + Left/Right

**Review by leolost2605 — APPROVED** [review]
I've confirmed the crash and this makes sense :)

**Comment by tintou** [comment]
Thank you, this was making me so angry!

**Pull request merged**
