### PR TITLE
#998: Allow apps to overlap workspace edges in multitasking view

### PR DESCRIPTION
**Pull request by JoseExposito**
Here is the required code to implement https://github.com/elementary/gala/issues/998

It is marked as WIP because @danrabbit might want to adjust some values.

padding

### CODE REVIEW

**Comment by cassidyjames** [comment]
@JoseExposito it might be related to/require fixing #997, but something I'm noticing here: the adjacent workspaces are now animated to way off screen which makes them not visible in the view (unless there's a maximized window). I think we want to keep them fairly visible, maybe somewhere in between master and that GNOME mockup.

Something else @elementary/ux needs to determine is if/how the bottom UI showing workspace previews should be adjusted, keeping in mind windows _can_ but won't _always_ go off the bottom of the workspace. But as-is it looks a little unbalanced to me when you don't have a window overlapping the bottom, and especially on larger displays.

Screenshot from 2020-12-22 11 12 36

**Comment by JoseExposito** [comment]
You are right. In order to make it visible, I can think of 2 options:

 - Make the space used by the app grid a little bit smaller
 - Or just make the workspaces closer

Have in mind that, when only one maximized window is open (IMHO that looks terrible) the wallpaper will not be displayed. This might make a little bit less intuitive that windows can be drag&dropped to the next/previous workspace.

**Comment by hanaral** [comment]
I'd like to chime in a little; I really am not seeing the benefits here, it seems to only bring in a few UX issues that need to be solved. I think that the current setup is fine, and has nice padding and even distances between the elements. 
_(as a seperate issue altogether there should be a smaller maximum window preview size, apps like dconf editor look like overinflated baloons)_

**Comment by JoseExposito** [comment]
Fixing #997 was required to adjust the constants in a sane way, so I solved that in a different PR and merged it here as well.

However, I agree with @hanaral , this is creating some UX issues that we need to fix, or just discard this idea. This is the current state of this branch:

Screenshot from 2020-12-27 12 43 25

When dark style is selected, there is not enough contrast between the windows and the gray area behind the wallpaper.

**Comment by danirabbit** [comment]
Closing since there's been no movement here for several years

**Pull request closed without merging**
