### PR TITLE
Switch to Meson and tidy up

### PR DESCRIPTION
**Pull request by codygarver**

### CODE REVIEW

**Comment by codygarver** [comment]
Ready for review.

**Comment by ricotz** [comment]
Is gnome-common still needed?

**Comment by codygarver** [comment]
`gnome-control` no longer needed, dropped. Ready for review.

**Comment by ricotz** [comment]
Do you want to bump the changelog version to accommodate for the dbg-migrations?

**Comment by codygarver** [comment]
Done.

**Pull request merged**
