### PR TITLE
Respect animation key in PiP

### LINKED ISSUE #510: PiP doesn't respect animations key
The buttons, bounce, and fade all still animate even if animations are disabled.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/72345228-pip-doesn-t-respect-animations-key?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F62872462&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by donadigo**
Fixes #510.
Depends on #513.

Respects the animation key so that when disabled, no animations are applied.

### CODE REVIEW

**Comment by tintou** [comment]
Note that #513 is bringing a property to WindowManager that would avoid you doing it yourself

**Comment by donadigo** [comment]
@tintou rebased on your branch.

**Comment by danrabbit** [comment]
Looks like #513 is merged. @donadigo care to update this branch?

**Comment by jeremypw** [comment]
@donadigo Closing as has conflicts and no recent activity following request to update. Please feel free to reopen (as draft) if you wish to continue working on it.

**Pull request closed without merging**
