### PR TITLE
X11: move dock window out of bounds when hidden

### PR DESCRIPTION
**Pull request by lenemter**
Fixes https://github.com/elementary/gala/issues/2101

This is very very bad code but I just couldn't find other solution. So far I tried:
* Minimizing window
* Using `_NET_WM_STATE_HIDDEN` (which is basically minimizing AFAIK)
* Blocking X11 window events by changing its event mask
* Using XShape extension

Nothing worked. If you know any other solution please let me know.

### CODE REVIEW

**Comment by leolost2605** [comment]
Tbh I think at some point we should just stop doing workarounds and instead go back to shipping plank for X since the whole infrastructure here (i.e. the new dock, the protocol, everything in /ShellClients) was never intended, tested or designed to work with X11 and just retrofitted into it with hopes it will work. 
And IMHO this whole thing just gets messier and messier and hard to maintain since always two scenarios have to be tested all at the risk of reducing quality for all sessions.
I'm not saying this point should be now but we should at least think about it.

**Comment by lenemter** [comment]
@leolost2605 I don't agree with that. If we don't adapt gala's code to X11, the same bugs will happen with Wingpanel when we'll implement https://github.com/elementary/wingpanel/issues/53 for example. And suddenly we need to ship two versions of the same component

**Comment by leolost2605** [comment]
Something like elementary/wingpanel#53 would be pretty much the only reason to support this and I think it's not worth polluting the codebase for that. Since there also doesn't seem to be a lot of movement regarding that I don't see it as a valid argument right now.
And even if something like elementary/wingpanel#53 would be agreed upon I'd argue that it can land in Wayland only because X11 can be considered deprecated and can hopefully be completely dropped very soon. So I don't think it's worth supporting it at the cost of a messy codebase especially since afaik apart from very specific edge cases Wayland provides a better experience as of today (tbh I also don't quite get why X is still the default for OS8).

**Comment by alainm23** [comment]
Regardless of the fact that the solution at the code level may be poor, this issue is causing a lot of noise. Several users have already reported it, and it’s even worse because X11 is being sent by default. What do you think about this, @danirabbit ?

**Review by alainm23 — APPROVED** [review]

**Pull request merged**
