### PR TITLE
Fix awkward two-finger scroll in multitasking view

### PR DESCRIPTION
**Pull request by GranPC**
Easing wasn't being correctly used when scrolling between workspaces with the touchpad in the multitasking view. There were two problems with this: scrolling seemed to lag behind the user's fingers sometimes, and letting go of the touchpad would almost always cause a jarring jump.

This little patch fixes both of these issues, making everything silky smooth.

If someone's not clear on what specifically we're solving here, I could record my screen and my hand on my touchpad before & after this patch. It really is night and day.

### CODE REVIEW

**Review by lenemter — COMMENTED** [review]
Fixes the issue. But is it necessary to introduce a one line one-time method? IMO it would be better to just put comment and `workspaces.set_easing_duration (0);` in the else block.

**Comment by GranPC** [comment]
Probably not. I created the method thinking I'd have to reset more state, but it turns out that one line was sufficient.

**Review by lenemter — APPROVED** [review]
Nice work! :heart:

**Comment by GranPC** [comment]
Thanks :) Only got a couple things left to fix here, and then Gala will be practically perfect for me! :rocket:

**Pull request merged**
