### PR TITLE
App: Implement Applications Management

### PR DESCRIPTION
**Pull request by tintou**
This allows us to completely replace libbamf in some specific cases (like system shell elements).

This PR is only opened for showing the intention, it's far from even starting to work.

### CODE REVIEW

**Comment by davidmhewitt** [comment]
As a quick note here, I wonder if there are any benefits of making the DBus API compatible with `org.gnome.shell.Introspect`: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/386d25e6f8ce11549526ea3776eb34138fcb3774/data/dbus-interfaces/org.gnome.Shell.Introspect.xml

I believe this is used for automated UI testing and some accessibility stuff, so perhaps useful?

**Comment by tintou** [comment]
> As a quick note here, I wonder if there are any benefits of making the DBus API compatible with `org.gnome.shell.Introspect`: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/386d25e6f8ce11549526ea3776eb34138fcb3774/data/dbus-interfaces/org.gnome.Shell.Introspect.xml
> 
> I believe this is used for automated UI testing and some accessibility stuff, so perhaps useful?

This is a private API that filters its users so I don't think that we should provide it

**Comment by tintou** [comment]
Removing the draft status as I'd like it to land with experimental status

**Comment by danirabbit** [comment]
Since this is only for use with other shell components I don’t see the harm in merging :)

**Review by danirabbit — APPROVED** [review]

**Pull request merged**
