### PR TITLE
Round corners of workspaces in multitasking view

### LINKED ISSUE #1545: Draw rounded corners on workspaces in multitasking view
### Problem

The corners of workspaces in the multitasking view are perfectly square and sharp even though we mask off corners of the desktop

### Proposal

Round the corners of workspaces in multitasking view with the same radius as we use for the whole desktop

### Prior Art (Optional)

GNOME Shell has rounded corners on its workspace previews these days

### PR DESCRIPTION
**Pull request by lenemter**
Closes #1545

### CODE REVIEW

**Comment by danirabbit** [comment]
If you zoom in a bunch you can see something is drawing a square here

Screenshot from 2023-10-30 20 06 12

**Comment by lenemter** [comment]
@danirabbit I increased outline border radius, does it look better on your screen?

**Comment by danirabbit** [comment]
@lenemter I think what's actually happening is that in the cairo rounded rectangle function the corners are drawn offset by like a half pixel which gives that weird aliasing. Gonna try to see if I can figure out how to fix it

**Comment by danirabbit** [comment]
@lenemter okay I don't know enough about cairo to fix this lol. But I think just making it 1px larger is what it should be and not 3px larger

**Comment by danirabbit** [comment]
Actually it should be smaller right? Like it doesn't make sense lol something is weird here
border-radius

**Review by danirabbit — APPROVED** [review]
We can fiddle with values later if we need to, rather not let perfect be the enemy of good :)

**Pull request merged**
