### PR TITLE
Update bindings to latest Mutter

### PR DESCRIPTION
**Pull request by tintou**
Update to mutter 42.beta

### CODE REVIEW

**Comment by decathorpe** [comment]
Can confirm that this compiles with mutter 42-beta. However, since it breaks compiling with mutter 42-alpha, it might be good to raise the requirement for libmutter-10 in meson.build to >= 42-beta?

**Comment by tintou** [comment]
@decathorpe Done :)

**Comment by decathorpe** [comment]
Looks good to me!

The only thing I'm not sure about is if meson's version comparison logic is smart enough to know that "42.0 > 42.beta". The meson documentation is rather vague in that respect.

**Comment by Conan-Kudo** [comment]
I'm pretty sure it is not...

**Comment by decathorpe** [comment]
Yeah that's fine with me 👍🏼

**Comment by Conan-Kudo** [comment]
LGTM

**Review by decathorpe — APPROVED** [review]

**Comment by decathorpe** [comment]
(forgot that I can do the approval 😅, sorry for the delay)

**Pull request merged**
