### PR TITLE
Improve multitasking view animation performance

### PR DESCRIPTION
**Pull request by GranPC**
This animation is currently super stuttery, especially on high-resolution devices. It was getting on my nerves. The reason it's slow is because we constantly reallocate resources instead of just scaling the actors we already have. On top of that, we also allocate a new texture every single time a `FramedBackground` was painted. Allocating stuff in the render loop is generally a bad idea.

So I removed a bunch of seemingly useless code and started caching resources in `FramedBackground` - and now it runs at 240fps on my laptop even with power savings enabled!

This is marked "draft" because I have no idea what I'm doing, and I assume there was a good reason for all the complexity inside `WindowClone.allocate`. That being said, after mercilessly ripping out all that code, everything seems to work OK on my end. Just opening this PR to get some feedback and hopefully understand why/whether this complexity is necessary.

### CODE REVIEW

**Comment by GranPC** [comment]
Oh, looks like this breaks the little focus ring around windows when you use the arrow keys. Working on it.

**Comment by GranPC** [comment]
Should be all good now.

**Review by tintou — APPROVED** [review]
Wow, thanks for working on this!

**Review by lenemter — CHANGES_REQUESTED** [review]
Focus ring around windows seems to be a bit misplaced.

`master`:
image

This branch:
image

**Comment by GranPC** [comment]
Great catch, thanks! Never claimed to be good at math :)

**Review by lenemter — APPROVED** [review]

**Comment by lenemter** [comment]
Looks good. I'm going to merge this because @tintou approved and no new issues found. Thank you for your work.

**Pull request merged**
