### PR TITLE
Multitasking view icon group DPI switch fix

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #483

Before:
screenshot from 2019-03-01 23 43 28

These first changes resizes IconGroup's on redraw, fixing part of the issue:
screenshot from 2019-03-03 16 37 28

I haven't figured out yet how these groups are positioned...

### CODE REVIEW

**Comment by peteruithoven** [comment]
Looks like it's layed out by a Clutter.BoxLayout: https://github.com/elementary/gala/blob/master/src/Widgets/IconGroupContainer.vala#L41
Why it's not updated when the size of it's children is updated I don't know. I also can't find a way to manually trigger an update.

**Comment by donadigo** [comment]
@peteruithoven I'm not sure if this will help you but MultitaskingView also takes care of repositioning the icon container: https://github.com/elementary/gala/blob/master/src/Widgets/MultitaskingView.vala#L255.

**Comment by peteruithoven** [comment]
But that's just the x axis. Aligning it in the middle of the screen.

**Comment by donadigo** [comment]
Yeah, you probably will have to reposition every group in the container itself manually.

**Comment by davidmhewitt** [comment]
Fixed in #1628 and #1629

**Pull request closed without merging**
